### ISSUE TITLE
Unable to curl petstore API

### ISSUE THREAD

**Issue by Docteur-RS** [IBM-Cloud/jpetstore-kubernetes#10]
Hey,

I was trying to CURL the petstore API by following the documentation at the original [java petstore](https://github.com/agoncal/agoncal-application-petstore-ee7#execute-the-sample)

For instance `curl -X GET http://SERVICE_IP/applicationPetstore/rest/categories` should work but I get
```shell
Error 404: javax.servlet.ServletException: java.io.FileNotFoundException: SRVE0190E: File not found: /applicationPetstore/rest/categories
```

On the other hand when I curl `curl -X GET http://SERVICE_IP` I get the front page in html so the jpetstore seems to be working ok ! 

**Is there some kind of config deactivating the API that I don't know of ?**  

---

Deploying using HELM

Any help would be appreciated :-)

**Comment by van-ibm** [comment]
The petstore implementation used in this project is more akin to one archived [here](http://www.java2s.com/Code/Java/Spring/SpringJPetStoresampleapplication.htm). I suspect the agoncal-application-petstore-ee7 repo has added behavior not contained in the older (i.e. 2005) version.

If you look at the [web.xml](https://github.com/IBM-Cloud/jpetstore-kubernetes/blob/master/jpetstore/war/WEB-INF/web.xml) and the `servlet-mapping` `url-pattern` pairs, these should be the only routes available.

The Watson integration in the demo actually reaches into the MySQL database rather than using an API from the petstore itself.  While that's not a good example of how to build a microservices, the purpose of this project was to take a very old legacy app and somehow integrate more modern technology. Direct service-to-DB communication was a means to do it quickly and easily.

If you're just smoke testing, anything with a `*.do` URL pattern should get a response.  If you want more API-like behavior, I don't believe that's implemented ...

**Comment by Docteur-RS** [comment]
Ok, it seems you are right ! ;-)

The only routes availble seems to be the one in web.xml and are the one used by the front...

As this was only for demo purposes I did a custom front and parsed the HTML like it was an API.

@van-ibm  thanks for your time !

---

For people searching an example of how to use the ***.do** path :
```shell
SERVICE_IP/shop/viewCategory.do?categoryId=CATS
```
